/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookSlugRouteImport } from './routes/book.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedSuperAdminRouteImport } from './routes/_authenticated.super-admin'
import { Route as AuthenticatedServicesRouteImport } from './routes/_authenticated.services'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated.schedule'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated.reports'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated.inbox'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedConversationsChatRouteImport } from './routes/_authenticated.conversations-chat'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated.contacts'
import { Route as AuthenticatedAiAgentRouteImport } from './routes/_authenticated.ai-agent'
import { Route as AuthenticatedSuperAdminWorkspacesRouteImport } from './routes/_authenticated.super-admin.workspaces'
import { Route as AuthenticatedSuperAdminUsersRouteImport } from './routes/_authenticated.super-admin.users'
import { Route as AuthenticatedSuperAdminIaRouteImport } from './routes/_authenticated.super-admin.ia'
import { Route as AuthenticatedSuperAdminHealthRouteImport } from './routes/_authenticated.super-admin.health'
import { Route as AuthenticatedSuperAdminBillingRouteImport } from './routes/_authenticated.super-admin.billing'
import { Route as AuthenticatedSettingsWorkspaceRouteImport } from './routes/_authenticated.settings.workspace'
import { Route as AuthenticatedSettingsWhatsappRouteImport } from './routes/_authenticated.settings.whatsapp'
import { Route as AuthenticatedSettingsTeamRouteImport } from './routes/_authenticated.settings.team'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated.settings.profile'
import { Route as AuthenticatedSettingsProfessionalsRouteImport } from './routes/_authenticated.settings.professionals'
import { Route as AuthenticatedSettingsBookingRouteImport } from './routes/_authenticated.settings.booking'
import { Route as AuthenticatedSettingsBillingRouteImport } from './routes/_authenticated.settings.billing'
import { Route as ApiPublicEvolutionInstanceIdRouteImport } from './routes/api/public/evolution.$instanceId'
import { Route as ApiPublicBookSlugRouteImport } from './routes/api/public/book.$slug'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSuperAdminRoute = AuthenticatedSuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedServicesRoute = AuthenticatedServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConversationsChatRoute =
  AuthenticatedConversationsChatRouteImport.update({
    id: '/conversations-chat',
    path: '/conversations-chat',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiAgentRoute = AuthenticatedAiAgentRouteImport.update({
  id: '/ai-agent',
  path: '/ai-agent',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuperAdminWorkspacesRoute =
  AuthenticatedSuperAdminWorkspacesRouteImport.update({
    id: '/workspaces',
    path: '/workspaces',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminUsersRoute =
  AuthenticatedSuperAdminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminIaRoute =
  AuthenticatedSuperAdminIaRouteImport.update({
    id: '/ia',
    path: '/ia',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminHealthRoute =
  AuthenticatedSuperAdminHealthRouteImport.update({
    id: '/health',
    path: '/health',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminBillingRoute =
  AuthenticatedSuperAdminBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSettingsWorkspaceRoute =
  AuthenticatedSettingsWorkspaceRouteImport.update({
    id: '/settings/workspace',
    path: '/settings/workspace',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsWhatsappRoute =
  AuthenticatedSettingsWhatsappRouteImport.update({
    id: '/settings/whatsapp',
    path: '/settings/whatsapp',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsTeamRoute =
  AuthenticatedSettingsTeamRouteImport.update({
    id: '/settings/team',
    path: '/settings/team',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsProfessionalsRoute =
  AuthenticatedSettingsProfessionalsRouteImport.update({
    id: '/settings/professionals',
    path: '/settings/professionals',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsBookingRoute =
  AuthenticatedSettingsBookingRouteImport.update({
    id: '/settings/booking',
    path: '/settings/booking',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsBillingRoute =
  AuthenticatedSettingsBillingRouteImport.update({
    id: '/settings/billing',
    path: '/settings/billing',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicEvolutionInstanceIdRoute =
  ApiPublicEvolutionInstanceIdRouteImport.update({
    id: '/api/public/evolution/$instanceId',
    path: '/api/public/evolution/$instanceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBookSlugRoute = ApiPublicBookSlugRouteImport.update({
  id: '/api/public/book/$slug',
  path: '/api/public/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/ai-agent': typeof AuthenticatedAiAgentRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/conversations-chat': typeof AuthenticatedConversationsChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/services': typeof AuthenticatedServicesRoute
  '/super-admin': typeof AuthenticatedSuperAdminRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/book/$slug': typeof BookSlugRoute
  '/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/settings/booking': typeof AuthenticatedSettingsBookingRoute
  '/settings/professionals': typeof AuthenticatedSettingsProfessionalsRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/settings/whatsapp': typeof AuthenticatedSettingsWhatsappRoute
  '/settings/workspace': typeof AuthenticatedSettingsWorkspaceRoute
  '/super-admin/billing': typeof AuthenticatedSuperAdminBillingRoute
  '/super-admin/health': typeof AuthenticatedSuperAdminHealthRoute
  '/super-admin/ia': typeof AuthenticatedSuperAdminIaRoute
  '/super-admin/users': typeof AuthenticatedSuperAdminUsersRoute
  '/super-admin/workspaces': typeof AuthenticatedSuperAdminWorkspacesRoute
  '/api/public/book/$slug': typeof ApiPublicBookSlugRoute
  '/api/public/evolution/$instanceId': typeof ApiPublicEvolutionInstanceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/ai-agent': typeof AuthenticatedAiAgentRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/conversations-chat': typeof AuthenticatedConversationsChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/services': typeof AuthenticatedServicesRoute
  '/super-admin': typeof AuthenticatedSuperAdminRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/book/$slug': typeof BookSlugRoute
  '/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/settings/booking': typeof AuthenticatedSettingsBookingRoute
  '/settings/professionals': typeof AuthenticatedSettingsProfessionalsRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/settings/whatsapp': typeof AuthenticatedSettingsWhatsappRoute
  '/settings/workspace': typeof AuthenticatedSettingsWorkspaceRoute
  '/super-admin/billing': typeof AuthenticatedSuperAdminBillingRoute
  '/super-admin/health': typeof AuthenticatedSuperAdminHealthRoute
  '/super-admin/ia': typeof AuthenticatedSuperAdminIaRoute
  '/super-admin/users': typeof AuthenticatedSuperAdminUsersRoute
  '/super-admin/workspaces': typeof AuthenticatedSuperAdminWorkspacesRoute
  '/api/public/book/$slug': typeof ApiPublicBookSlugRoute
  '/api/public/evolution/$instanceId': typeof ApiPublicEvolutionInstanceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/ai-agent': typeof AuthenticatedAiAgentRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/conversations-chat': typeof AuthenticatedConversationsChatRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/_authenticated/services': typeof AuthenticatedServicesRoute
  '/_authenticated/super-admin': typeof AuthenticatedSuperAdminRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/book/$slug': typeof BookSlugRoute
  '/_authenticated/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/_authenticated/settings/booking': typeof AuthenticatedSettingsBookingRoute
  '/_authenticated/settings/professionals': typeof AuthenticatedSettingsProfessionalsRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/_authenticated/settings/whatsapp': typeof AuthenticatedSettingsWhatsappRoute
  '/_authenticated/settings/workspace': typeof AuthenticatedSettingsWorkspaceRoute
  '/_authenticated/super-admin/billing': typeof AuthenticatedSuperAdminBillingRoute
  '/_authenticated/super-admin/health': typeof AuthenticatedSuperAdminHealthRoute
  '/_authenticated/super-admin/ia': typeof AuthenticatedSuperAdminIaRoute
  '/_authenticated/super-admin/users': typeof AuthenticatedSuperAdminUsersRoute
  '/_authenticated/super-admin/workspaces': typeof AuthenticatedSuperAdminWorkspacesRoute
  '/api/public/book/$slug': typeof ApiPublicBookSlugRoute
  '/api/public/evolution/$instanceId': typeof ApiPublicEvolutionInstanceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/ai-agent'
    | '/contacts'
    | '/conversations-chat'
    | '/dashboard'
    | '/inbox'
    | '/reports'
    | '/schedule'
    | '/services'
    | '/super-admin'
    | '/auth/callback'
    | '/book/$slug'
    | '/settings/billing'
    | '/settings/booking'
    | '/settings/professionals'
    | '/settings/profile'
    | '/settings/team'
    | '/settings/whatsapp'
    | '/settings/workspace'
    | '/super-admin/billing'
    | '/super-admin/health'
    | '/super-admin/ia'
    | '/super-admin/users'
    | '/super-admin/workspaces'
    | '/api/public/book/$slug'
    | '/api/public/evolution/$instanceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/ai-agent'
    | '/contacts'
    | '/conversations-chat'
    | '/dashboard'
    | '/inbox'
    | '/reports'
    | '/schedule'
    | '/services'
    | '/super-admin'
    | '/auth/callback'
    | '/book/$slug'
    | '/settings/billing'
    | '/settings/booking'
    | '/settings/professionals'
    | '/settings/profile'
    | '/settings/team'
    | '/settings/whatsapp'
    | '/settings/workspace'
    | '/super-admin/billing'
    | '/super-admin/health'
    | '/super-admin/ia'
    | '/super-admin/users'
    | '/super-admin/workspaces'
    | '/api/public/book/$slug'
    | '/api/public/evolution/$instanceId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/ai-agent'
    | '/_authenticated/contacts'
    | '/_authenticated/conversations-chat'
    | '/_authenticated/dashboard'
    | '/_authenticated/inbox'
    | '/_authenticated/reports'
    | '/_authenticated/schedule'
    | '/_authenticated/services'
    | '/_authenticated/super-admin'
    | '/auth/callback'
    | '/book/$slug'
    | '/_authenticated/settings/billing'
    | '/_authenticated/settings/booking'
    | '/_authenticated/settings/professionals'
    | '/_authenticated/settings/profile'
    | '/_authenticated/settings/team'
    | '/_authenticated/settings/whatsapp'
    | '/_authenticated/settings/workspace'
    | '/_authenticated/super-admin/billing'
    | '/_authenticated/super-admin/health'
    | '/_authenticated/super-admin/ia'
    | '/_authenticated/super-admin/users'
    | '/_authenticated/super-admin/workspaces'
    | '/api/public/book/$slug'
    | '/api/public/evolution/$instanceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BookSlugRoute: typeof BookSlugRoute
  ApiPublicBookSlugRoute: typeof ApiPublicBookSlugRoute
  ApiPublicEvolutionInstanceIdRoute: typeof ApiPublicEvolutionInstanceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/super-admin': {
      id: '/_authenticated/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof AuthenticatedSuperAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/services': {
      id: '/_authenticated/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conversations-chat': {
      id: '/_authenticated/conversations-chat'
      path: '/conversations-chat'
      fullPath: '/conversations-chat'
      preLoaderRoute: typeof AuthenticatedConversationsChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-agent': {
      id: '/_authenticated/ai-agent'
      path: '/ai-agent'
      fullPath: '/ai-agent'
      preLoaderRoute: typeof AuthenticatedAiAgentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/super-admin/workspaces': {
      id: '/_authenticated/super-admin/workspaces'
      path: '/workspaces'
      fullPath: '/super-admin/workspaces'
      preLoaderRoute: typeof AuthenticatedSuperAdminWorkspacesRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/users': {
      id: '/_authenticated/super-admin/users'
      path: '/users'
      fullPath: '/super-admin/users'
      preLoaderRoute: typeof AuthenticatedSuperAdminUsersRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/ia': {
      id: '/_authenticated/super-admin/ia'
      path: '/ia'
      fullPath: '/super-admin/ia'
      preLoaderRoute: typeof AuthenticatedSuperAdminIaRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/health': {
      id: '/_authenticated/super-admin/health'
      path: '/health'
      fullPath: '/super-admin/health'
      preLoaderRoute: typeof AuthenticatedSuperAdminHealthRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/billing': {
      id: '/_authenticated/super-admin/billing'
      path: '/billing'
      fullPath: '/super-admin/billing'
      preLoaderRoute: typeof AuthenticatedSuperAdminBillingRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/settings/workspace': {
      id: '/_authenticated/settings/workspace'
      path: '/settings/workspace'
      fullPath: '/settings/workspace'
      preLoaderRoute: typeof AuthenticatedSettingsWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/whatsapp': {
      id: '/_authenticated/settings/whatsapp'
      path: '/settings/whatsapp'
      fullPath: '/settings/whatsapp'
      preLoaderRoute: typeof AuthenticatedSettingsWhatsappRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/team': {
      id: '/_authenticated/settings/team'
      path: '/settings/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof AuthenticatedSettingsTeamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/professionals': {
      id: '/_authenticated/settings/professionals'
      path: '/settings/professionals'
      fullPath: '/settings/professionals'
      preLoaderRoute: typeof AuthenticatedSettingsProfessionalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/booking': {
      id: '/_authenticated/settings/booking'
      path: '/settings/booking'
      fullPath: '/settings/booking'
      preLoaderRoute: typeof AuthenticatedSettingsBookingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/billing': {
      id: '/_authenticated/settings/billing'
      path: '/settings/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AuthenticatedSettingsBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/evolution/$instanceId': {
      id: '/api/public/evolution/$instanceId'
      path: '/api/public/evolution/$instanceId'
      fullPath: '/api/public/evolution/$instanceId'
      preLoaderRoute: typeof ApiPublicEvolutionInstanceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/book/$slug': {
      id: '/api/public/book/$slug'
      path: '/api/public/book/$slug'
      fullPath: '/api/public/book/$slug'
      preLoaderRoute: typeof ApiPublicBookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedSuperAdminRouteChildren {
  AuthenticatedSuperAdminBillingRoute: typeof AuthenticatedSuperAdminBillingRoute
  AuthenticatedSuperAdminHealthRoute: typeof AuthenticatedSuperAdminHealthRoute
  AuthenticatedSuperAdminIaRoute: typeof AuthenticatedSuperAdminIaRoute
  AuthenticatedSuperAdminUsersRoute: typeof AuthenticatedSuperAdminUsersRoute
  AuthenticatedSuperAdminWorkspacesRoute: typeof AuthenticatedSuperAdminWorkspacesRoute
}

const AuthenticatedSuperAdminRouteChildren: AuthenticatedSuperAdminRouteChildren =
  {
    AuthenticatedSuperAdminBillingRoute: AuthenticatedSuperAdminBillingRoute,
    AuthenticatedSuperAdminHealthRoute: AuthenticatedSuperAdminHealthRoute,
    AuthenticatedSuperAdminIaRoute: AuthenticatedSuperAdminIaRoute,
    AuthenticatedSuperAdminUsersRoute: AuthenticatedSuperAdminUsersRoute,
    AuthenticatedSuperAdminWorkspacesRoute:
      AuthenticatedSuperAdminWorkspacesRoute,
  }

const AuthenticatedSuperAdminRouteWithChildren =
  AuthenticatedSuperAdminRoute._addFileChildren(
    AuthenticatedSuperAdminRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAiAgentRoute: typeof AuthenticatedAiAgentRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedConversationsChatRoute: typeof AuthenticatedConversationsChatRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedServicesRoute: typeof AuthenticatedServicesRoute
  AuthenticatedSuperAdminRoute: typeof AuthenticatedSuperAdminRouteWithChildren
  AuthenticatedSettingsBillingRoute: typeof AuthenticatedSettingsBillingRoute
  AuthenticatedSettingsBookingRoute: typeof AuthenticatedSettingsBookingRoute
  AuthenticatedSettingsProfessionalsRoute: typeof AuthenticatedSettingsProfessionalsRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedSettingsTeamRoute: typeof AuthenticatedSettingsTeamRoute
  AuthenticatedSettingsWhatsappRoute: typeof AuthenticatedSettingsWhatsappRoute
  AuthenticatedSettingsWorkspaceRoute: typeof AuthenticatedSettingsWorkspaceRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAiAgentRoute: AuthenticatedAiAgentRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedConversationsChatRoute: AuthenticatedConversationsChatRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedServicesRoute: AuthenticatedServicesRoute,
  AuthenticatedSuperAdminRoute: AuthenticatedSuperAdminRouteWithChildren,
  AuthenticatedSettingsBillingRoute: AuthenticatedSettingsBillingRoute,
  AuthenticatedSettingsBookingRoute: AuthenticatedSettingsBookingRoute,
  AuthenticatedSettingsProfessionalsRoute:
    AuthenticatedSettingsProfessionalsRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  AuthenticatedSettingsTeamRoute: AuthenticatedSettingsTeamRoute,
  AuthenticatedSettingsWhatsappRoute: AuthenticatedSettingsWhatsappRoute,
  AuthenticatedSettingsWorkspaceRoute: AuthenticatedSettingsWorkspaceRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BookSlugRoute: BookSlugRoute,
  ApiPublicBookSlugRoute: ApiPublicBookSlugRoute,
  ApiPublicEvolutionInstanceIdRoute: ApiPublicEvolutionInstanceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
